/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DcfInputs = IDL.Record({
  'weightedAveCostOfCapital' : IDL.Float64,
  'sharesOutstanding' : IDL.Float64,
  'forecastedFCF' : IDL.Float64,
  'terminalYears' : IDL.Int,
  'actualSharePrice' : IDL.Float64,
  'revenueLastYear' : IDL.Float64,
  'revenueLastQuarter' : IDL.Float64,
  'perpetualGrowthRate' : IDL.Float64,
});
export const DcfOutputs = IDL.Record({
  'totalMarketCap' : IDL.Float64,
  'intrinsicPricePerShare' : IDL.Float64,
  'adjustedValuation' : IDL.Float64,
  'actualPerShare' : IDL.Float64,
  'riskDiscount' : IDL.Float64,
  'profitability' : IDL.Float64,
  'industryGrowth' : IDL.Float64,
  'totalShares' : IDL.Float64,
});

export const idlService = IDL.Service({
  'processDcf' : IDL.Func([DcfInputs], [DcfOutputs], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DcfInputs = IDL.Record({
    'weightedAveCostOfCapital' : IDL.Float64,
    'sharesOutstanding' : IDL.Float64,
    'forecastedFCF' : IDL.Float64,
    'terminalYears' : IDL.Int,
    'actualSharePrice' : IDL.Float64,
    'revenueLastYear' : IDL.Float64,
    'revenueLastQuarter' : IDL.Float64,
    'perpetualGrowthRate' : IDL.Float64,
  });
  const DcfOutputs = IDL.Record({
    'totalMarketCap' : IDL.Float64,
    'intrinsicPricePerShare' : IDL.Float64,
    'adjustedValuation' : IDL.Float64,
    'actualPerShare' : IDL.Float64,
    'riskDiscount' : IDL.Float64,
    'profitability' : IDL.Float64,
    'industryGrowth' : IDL.Float64,
    'totalShares' : IDL.Float64,
  });
  
  return IDL.Service({
    'processDcf' : IDL.Func([DcfInputs], [DcfOutputs], []),
  });
};

export const init = ({ IDL }) => { return []; };