/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface VisitorDetails {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'mobile' : string,
  'timestamp' : bigint,
}
export interface DcfInputs {
  'weightedAveCostOfCapital' : number,
  'sharesOutstanding' : number,
  'forecastedFCF' : number,
  'terminalYears' : bigint,
  'actualSharePrice' : number,
  'revenueLastYear' : number,
  'revenueLastQuarter' : number,
  'perpetualGrowthRate' : number,
}
export interface DcfOutputs {
  'totalMarketCap' : number,
  'intrinsicPricePerShare' : number,
  'adjustedValuation' : number,
  'actualPerShare' : number,
  'riskDiscount' : number,
  'profitability' : number,
  'totalShares' : number,
}
export interface UserProfile {
  'mobileNumber' : string,
  'lastName' : string,
  'firstName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllVisitorDetails' : ActorMethod<[], Array<VisitorDetails>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNumAllUserProfiles' : ActorMethod<[], [] | [bigint]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processDcf' : ActorMethod<[DcfInputs], DcfOutputs>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
  'submitVisitorDetails' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];