/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'mobileNumber' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const DcfInputs = IDL.Record({
  'weightedAveCostOfCapital' : IDL.Float64,
  'sharesOutstanding' : IDL.Float64,
  'forecastedFCF' : IDL.Float64,
  'terminalYears' : IDL.Int,
  'actualSharePrice' : IDL.Float64,
  'revenueLastYear' : IDL.Float64,
  'revenueLastQuarter' : IDL.Float64,
  'perpetualGrowthRate' : IDL.Float64,
});
export const DcfOutputs = IDL.Record({
  'totalMarketCap' : IDL.Float64,
  'intrinsicPricePerShare' : IDL.Float64,
  'adjustedValuation' : IDL.Float64,
  'actualPerShare' : IDL.Float64,
  'riskDiscount' : IDL.Float64,
  'profitability' : IDL.Float64,
  'totalShares' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNumAllUserProfiles' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processDcf' : IDL.Func([DcfInputs], [DcfOutputs], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'mobileNumber' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const DcfInputs = IDL.Record({
    'weightedAveCostOfCapital' : IDL.Float64,
    'sharesOutstanding' : IDL.Float64,
    'forecastedFCF' : IDL.Float64,
    'terminalYears' : IDL.Int,
    'actualSharePrice' : IDL.Float64,
    'revenueLastYear' : IDL.Float64,
    'revenueLastQuarter' : IDL.Float64,
    'perpetualGrowthRate' : IDL.Float64,
  });
  const DcfOutputs = IDL.Record({
    'totalMarketCap' : IDL.Float64,
    'intrinsicPricePerShare' : IDL.Float64,
    'adjustedValuation' : IDL.Float64,
    'actualPerShare' : IDL.Float64,
    'riskDiscount' : IDL.Float64,
    'profitability' : IDL.Float64,
    'totalShares' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNumAllUserProfiles' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processDcf' : IDL.Func([DcfInputs], [DcfOutputs], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };